language: python
python:
- 3.6
before_install:
- openssl aes-256-cbc -K $encrypted_2834ca410025_key -iv $encrypted_2834ca410025_iv
  -in secret.tar.enc -out secret.tar -d
install:
- pip install -r requirements.txt
before_script:
- cd instagram
script:
- python manage.py test
