# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 04:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20171019_0641'),
        ('member', '0003_auto_20171019_0626'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='like_posts',
            field=models.ManyToManyField(to='post.Post'),
        ),
    ]
