# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 07:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0008_user_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user',
            new_name='user_type',
        ),
    ]
