# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0009_auto_20171024_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
